from tkinter import *
import pyautogui as py
from selenium import webdriver
import time
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from nfc import *
import json


options = webdriver.ChromeOptions()
options.add_argument("--disable-extensions")
options.add_argument("--start-maximized")
options.add_argument("--disable-popup-blocking")
#options.add_argument("--headless")
#options.add_argument("--disable_gpu")
options.add_argument('--disable-notifications')

root = Tk()
backr = PhotoImage(file='postat.png')

root.geometry("1100x600") 

root.title('Почта России')


def change_language():
    py.moveTo(1007,9)
    py.click()

def upper_letter():
    py.press('capslock')


def nfc():
    while True:
        
        uid = pn532.read_passive_target(timeout=0.5)
        print(".", end="")
        if uid is None:
            continue
        else:
            print("Found card with UID:",[hex(i) for i in uid])
        if uid == bytearray(b'\x93\xe3\xb6\t'):
            page4()
            break

def page0():
    
    page0label.place(x=55,y=0)
    page0label2.place(x=200,y=130)
    page0label3.place(x=440,y=180)
    page0entry1.place(x=500,y=100,height=50)
    page0entry2.place(x=500,y=160,height=50)
    page0button1.place(x=500,y=220)
    page0button2.place(x=650,y=220)
    page1btn.place_forget()
    page1label.place_forget()
    page1button2.place_forget()
    page1button3.place_forget()
    page2label7.place_forget()
    page2entry6.place_forget()
    harfqq.place(x=10,y=350)
    harfww.place(x=70,y=350)
    harfee.place(x=130,y=350)
    harfrr.place(x=190,y=350)
    harftt.place(x=245,y=350)
    harfyy.place(x=300,y=350) 
    harfuu.place(x=355,y=350)
    harfii.place(x=410,y=350)
    harfoo.place(x=465,y=350)
    harfpp.place(x=520,y=350)
    harfaa.place(x=10,y=420)
    harfss.place(x=70,y=420)
    harfdd.place(x=130,y=420)
    harffff.place(x=192,y=420)
    harfgg.place(x=245,y=420)
    harfhh.place(x=300,y=420)
    harfjj.place(x=355,y=420)
    harfkk.place(x=410,y=420)
    harfll.place(x=465,y=420)   
    harfooo.place(x=520,y=420)   
    harfzz.place(x=10,y=490)   
    harfxxxx.place(x=70,y=490)    
    harfcc.place(x=130,y=490)
    harfvv.place(x=192,y=490)
    harfbb.place(x=245,y=490)
    harfnn.place(x=300,y=490)
    harfmm.place(x=355,y=490)
    probell.place(x=410,y=490)
    sayii1.place(x=700,y=355)
    sayii2.place(x=770,y=355)
    sayii3.place(x=840,y=355)
    sayii4.place(x=700,y=425)
    sayii5.place(x=770,y=425)
    sayii6.place(x=840,y=425)
    sayii7.place(x=700,y=495)
    sayii8.place(x=752,y=495)
    sayii9.place(x=805,y=495)
    sayii0.place(x=855,y=495)
    lang.place(x=930,y=495)
    capsl.place(x=930,y=420)
    page2label7.place_forget()
    page2entry6.place_forget()
    page1label0.place_forget()

def page1():
    capsl.place_forget()
    page3label.pack_forget()
    page2label.pack_forget()
    page2label2.place_forget()
    page2entry1.place_forget()
    page2label3.place_forget()
    page2entry2.place_forget()
    page2label4.place_forget()
    page2entry3.place_forget()
    page2label5.place_forget()
    page2entry4.place_forget()
    page2button1.place_forget()
    page2label.pack_forget()
    page1btn.place(x=550,y=190)
    page1label.place(x=300,y=50)
    page1button2.place(x=220,y=190)
    page2button2.place_forget()
    page3label.place_forget()
    page3label2.place_forget()
    page3entry1.place_forget()
    page3label3.place_forget()
    page3entry2.place_forget()
    page3label4.place_forget()
    page3entry3.place_forget()
    page3label5.place_forget()
    page3entry4.place_forget()
    page3button1.place_forget()
    page3button2.place_forget()
    page2label6.place_forget()
    page2entry5.place_forget()
    page3label6.place_forget()
    page3entry5.place_forget()
    page0label.place_forget()
    page0label2.place_forget()
    page0label3.place_forget()
    page0entry1.place_forget()
    page0entry2.place_forget()
    page0button1.place_forget()
    page1button3.place(x=430,y=350)
    harfqq.place_forget()
    harfww.place_forget()
    harfee.place_forget()
    harfrr.place_forget()
    harftt.place_forget()
    harfyy.place_forget()
    harfuu.place_forget()
    harfii.place_forget()
    harfoo.place_forget()
    harfpp.place_forget()
    harfaa.place_forget()
    harfss.place_forget()
    harfdd.place_forget()
    harffff.place_forget()
    harfgg.place_forget()
    harfhh.place_forget()
    harfjj.place_forget()
    harfkk.place_forget()
    harfll.place_forget()
    harfooo.place_forget()
    harfzz.place_forget()
    harfxxxx.place_forget()
    harfcc.place_forget()
    harfvv.place_forget()
    harfbb.place_forget()
    harfnn.place_forget()
    harfmm.place_forget()
    probell.place_forget()
    sayii1.place_forget()
    sayii2.place_forget()
    sayii3.place_forget()
    sayii4.place_forget()
    sayii5.place_forget()
    sayii6.place_forget()
    sayii7.place_forget()
    sayii8.place_forget()
    sayii9.place_forget()
    sayii0.place_forget()
    lang.place_forget()

    harfq.place_forget()
    harfw.place_forget()
    harfe.place_forget()
    harfr.place_forget()
    harft.place_forget()
    harfy.place_forget()
    harfu.place_forget()
    harfi.place_forget()
    harfo.place_forget()
    harfp.place_forget()
    harfx.place_forget()
    harff.place_forget()
    harfa.place_forget()
    harfs.place_forget()
    harfd.place_forget()
    harfddd.place_forget()
    harfrrr.place_forget()
    harfff.place_forget()
    harfg.place_forget()
    harfh.place_forget()
    harfj.place_forget()
    harfk.place_forget()
    harfl.place_forget()
    harfoo.place_forget()
    harfz.place_forget()
    harfxxx.place_forget()
    harfc.place_forget()
    harfv.place_forget()
    harfb.place_forget()
    harfn.place_forget()
    harfm.place_forget()
    probel.place_forget()
    sayi1.place_forget()
    sayi2.place_forget()
    sayi3.place_forget()
    sayi4.place_forget()
    sayi5.place_forget()
    sayi6.place_forget()
    sayi7.place_forget()
    sayi8.place_forget()
    sayi9.place_forget()
    sayi0.place_forget()
    page2label7.place_forget()
    page2entry6.place_forget()
    harfjjj.place_forget()
    harfeee.place_forget()
    harfoooo.place_forget()
    page1label0.place(x=17,y=10)

def page2():
    page1btn.place_forget()
    page1label.place_forget()
    page1button2.place_forget()
    page2label.pack()
    page2label2.place(x=5,y=100)
    page2entry1.place(x=5,y=130,height=50)
    page2label3.place(x=5,y=190)
    page2entry2.place(x=5,y=210,height=50)
    page2label4.place(x=420,y=110)
    page2entry3.place(x=420,y=130,height=50)
    page2label5.place(x=420,y=190)
    page2entry4.place(x=420,y=210,height=50)
    page2button1.place(x=660,y=275)
    page2button2.place(x=475,y=275)
    page2label6.place(x=5,y=270)
    page2entry5.place(x=5,y=290,height=50)
    page2label7.place(x=840,y=110)
    page2entry6.place(x=840,y=130,height=50)
    page1button3.place_forget()
    harfq.place(x=10,y=350)
    harfw.place(x=65,y=350)
    harfe.place(x=120,y=350)
    harfr.place(x=175,y=350)
    harft.place(x=230,y=350)
    harfy.place(x=285,y=350)
    harfu.place(x=340,y=350)
    harfi.place(x=390,y=350)
    harfo.place(x=450,y=350)
    harfp.place(x=510,y=350)
    harfx.place(x=560,y=350)
    harff.place(x=615,y=350)
    harfa.place(x=10,y=420)
    harfs.place(x=65,y=420)
    harfd.place(x=120,y=420)
    harfff.place(x=175,y=420)
    harfg.place(x=230,y=420)
    harfh.place(x=285,y=420)
    harfj.place(x=340,y=420)
    harfk.place(x=395,y=420)
    harfl.place(x=450,y=420)
    harfjjj.place(x=505,y=420)
    harfeee.place(x=560,y=420)
    harfoooo.place(x=615,y=420)
    harfz.place(x=10,y=490)
    harfxxx.place(x=65,y=490)
    harfc.place(x=120,y=490)
    harfv.place(x=175,y=490)
    harfb.place(x=230,y=490)
    harfn.place(x=285,y=490)
    harfm.place(x=340,y=490)
    harfddd.place(x=395,y=490)
    harfrrr.place (x=450,y=490)
    probel.place(x=515,y=490)
    
    sayi1.place(x=790,y=355)
    sayi2.place(x=860,y=355)
    sayi3.place(x=930,y=355)
    sayi4.place(x=790,y=425)
    sayi5.place(x=860,y=425)
    sayi6.place(x=930,y=425)
    sayi7.place(x=790,y=495)
    sayi8.place(x=843,y=495)
    sayi9.place(x=895,y=495)
    sayi0.place(x=945,y=495)
    harfqq.place_forget()
    harfww.place_forget()
    harfee.place_forget()
    harfrr.place_forget()
    harftt.place_forget()
    harfyy.place_forget()
    harfii.place_forget()
    harfoo.place_forget()
    harfpp.place_forget()
    harfaa.place_forget()
    harfss.place_forget()
    harfdd.place_forget()
    harffff.place_forget()
    harfgg.place_forget()
    harfhh.place_forget()
    harfjj.place_forget()
    harfkk.place_forget()
    harfll.place_forget()
    harfzz.place_forget()
    harfxxxx.place_forget()
    harfcc.place_forget()
    harfvv.place_forget()
    harfbb.place_forget()
    harfnn.place_forget()
    harfmm.place_forget()
    probell.place_forget()
    sayii1.place_forget()
    sayii2.place_forget()
    sayii3.place_forget()
    sayii4.place_forget()
    sayii5.place_forget()
    sayii6.place_forget()
    sayii7.place_forget()
    sayii8.place_forget()
    sayii9.place_forget()
    sayii0.place_forget()
    lang.place_forget()
    page1label0.place_forget()
    
def page3():
    page2label7.place_forget()
    page2entry6.place_forget()
    page2label.place_forget()
    page1btn.place_forget()
    page1label.place_forget()
    page1button2.place_forget()
    page2entry1.place_forget()
    page2entry2.place_forget()
    page2button2.place_forget()
    page2label.place_forget()
    page2label2.place_forget()
    page2entry1.place_forget()
    page2label3.place_forget()
    page2entry2.place_forget()
    page2label4.place_forget()
    page2entry3.place_forget()
    page2label5.place_forget()
    page2entry4.place_forget()
    page2button1.place_forget()
    page2button2.place_forget()
    page3label.pack()
    page3label2.place(x=5,y=100)
    page3entry1.place(x=5,y=130,height=50)
    page3label3.place(x=5,y=190)
    page3entry2.place(x=5,y=210,height=50)
    page3label4.place(x=430,y=110)
    page3entry3.place(x=430,y=130,height=50)
    page3label5.place(x=430,y=190)
    page3entry4.place(x=430,y=210,height=50)
    page3button1.place(x=645,y=290)
    page3button2.place(x=440,y=290,height=50)
    page3label6.place(x=5,y=270)
    page3entry5.place(x=5,y=290,height=50)
    page1button3.place_forget()
    harfq.place(x=10,y=350)
    harfw.place(x=65,y=350)
    harfe.place(x=120,y=350)
    harfr.place(x=175,y=350)
    harft.place(x=230,y=350)
    harfy.place(x=285,y=350)
    harfu.place(x=340,y=350)
    harfi.place(x=390,y=350)
    harfo.place(x=450,y=350)
    harfp.place(x=510,y=350)
    harfx.place(x=560,y=350)
    harff.place(x=615,y=350)
    harfa.place(x=10,y=420)
    harfs.place(x=65,y=420)
    harfd.place(x=120,y=420)
    harfff.place(x=175,y=420)
    harfg.place(x=230,y=420)
    harfh.place(x=285,y=420)
    harfj.place(x=340,y=420)
    harfk.place(x=395,y=420)
    harfl.place(x=450,y=420)
    harfjjj.place(x=505,y=420)
    harfeee.place(x=560,y=420)
    harfoooo.place(x=620,y=420)
    harfz.place(x=10,y=490)
    harfxxx.place(x=65,y=490)
    harfc.place(x=120,y=490)
    harfv.place(x=175,y=490)
    harfb.place(x=230,y=490)
    harfn.place(x=285,y=490)
    harfm.place(x=340,y=490)
    harfddd.place(x=395,y=490)
    harfrrr.place (x=450,y=490)
    probel.place(x=520,y=490)
    sayi1.place(x=790,y=355)
    sayi2.place(x=860,y=355)
    sayi3.place(x=930,y=355)
    sayi4.place(x=790,y=425)
    sayi5.place(x=860,y=425)
    sayi6.place(x=930,y=425)
    sayi7.place(x=790,y=495)
    sayi8.place(x=843,y=495)
    sayi9.place(x=895,y=495)
    sayi0.place(x=945,y=495)
    harfqq.place_forget()
    harfww.place_forget()
    harfee.place_forget()
    harfrr.place_forget()
    harftt.place_forget()
    harfyy.place_forget()
    harfii.place_forget()
    harfooo.place_forget()
    harfpp.place_forget()
    harfaa.place_forget()
    harfss.place_forget()
    harfdd.place_forget()
    harffff.place_forget()
    harfgg.place_forget()
    harfhh.place_forget()
    harfjj.place_forget()
    harfkk.place_forget()
    harfll.place_forget()
    harfzz.place_forget()
    harfxxxx.place_forget()
    harfcc.place_forget()
    harfvv.place_forget()
    harfbb.place_forget()
    harfnn.place_forget()
    harfmm.place_forget()
    probell.place_forget()
    sayii1.place_forget()
    sayii2.place_forget()
    sayii3.place_forget()
    sayii4.place_forget()
    sayii5.place_forget()
    sayii6.place_forget()
    sayii7.place_forget()
    sayii8.place_forget()
    sayii9.place_forget()
    sayii0.place_forget()
    lang.place_forget()
    page1label0.place_forget()
        
    
def page4():
    page4label0.place(x=400,y=15)
    page4label1.place(x=100,y=85)
    page4entry1.place(x=100,y=105)
    page4label2.place(x=580,y=85)
    page4lentry2.place(x=580,y=105)
    page4label3.place(x=100,y=175)
    page4entry3.place(x=100,y=200)
    page4label4.place(x=580,y=175)
    page4entry4.place(x=580,y=200)
    page4button1.place(x=200,y=260)
    page4button2.place(x=450,y=260)
    w.place(x=650,y=260)
    page0label2.place_forget()
    page0label3.place_forget()
    page0entry1.place_forget()
    page0entry2.place_forget()
    page0button1.place_forget()
    page0button2.place_forget()
    harfqq.place_forget()
    harfww.place_forget()
    harfee.place_forget()
    harfrr.place_forget()
    harftt.place_forget()
    harfyy.place_forget()
    harfii.place_forget()
    harfooo.place_forget()
    harfoo.place_forget()
    harfuu.place_forget()
    harfpp.place_forget()
    harfaa.place_forget()
    harfss.place_forget()
    harfdd.place_forget()
    harffff.place_forget()
    harfgg.place_forget()
    harfhh.place_forget()
    harfjj.place_forget()
    harfkk.place_forget()
    harfll.place_forget()
    harfzz.place_forget()
    harfxxxx.place_forget()
    harfcc.place_forget()
    harfvv.place_forget()
    harfbb.place_forget()
    harfnn.place_forget()
    harfmm.place_forget()
    probell.place_forget()
    sayii1.place_forget()
    sayii2.place_forget()
    sayii3.place_forget()
    sayii4.place_forget()
    sayii5.place_forget()
    sayii6.place_forget()
    sayii7.place_forget()
    sayii8.place_forget()
    sayii9.place_forget()
    sayii0.place_forget()
    lang.place(x=680,y=350)
    capsl.place_forget()
    harfq.place(x=10,y=350)
    harfw.place(x=65,y=350)
    harfe.place(x=120,y=350)
    harfr.place(x=175,y=350)
    harft.place(x=230,y=350)
    harfy.place(x=285,y=350)
    harfu.place(x=340,y=350)
    harfi.place(x=390,y=350)
    harfo.place(x=450,y=350)
    harfp.place(x=510,y=350)
    harfx.place(x=560,y=350)
    harff.place(x=615,y=350)
    harfa.place(x=10,y=420)
    harfs.place(x=65,y=420)
    harfd.place(x=120,y=420)
    harfff.place(x=175,y=420)
    harfg.place(x=230,y=420)
    harfh.place(x=285,y=420)
    harfj.place(x=340,y=420)
    harfk.place(x=395,y=420)
    harfl.place(x=450,y=420)
    harfjjj.place(x=505,y=420)
    harfeee.place(x=560,y=420)
    harfoooo.place(x=615,y=420)
    harfz.place(x=10,y=490)
    harfxxx.place(x=65,y=490)
    harfc.place(x=120,y=490)
    harfv.place(x=175,y=490)
    harfb.place(x=230,y=490)
    harfn.place(x=285,y=490)
    harfm.place(x=340,y=490)
    harfddd.place(x=395,y=490)
    harfrrr.place (x=450,y=490)
    probel.place(x=515,y=490)
    
    sayi1.place(x=790,y=355)
    sayi2.place(x=860,y=355)
    sayi3.place(x=930,y=355)
    sayi4.place(x=790,y=425)
    sayi5.place(x=860,y=425)
    sayi6.place(x=930,y=425)
    sayi7.place(x=790,y=495)
    sayi8.place(x=843,y=495)
    sayi9.place(x=895,y=495)
    sayi0.place(x=945,y=495)
    

def posilka():
    driver=webdriver.Chrome(options=options)
    #driver=webdriver.Chrome('/lib/chromium-browser/chromedriver',options=options)
    driver.get('https://www.pochta.ru/api/auth/login')
    logins = page0entry1.get()
    password = page0entry2.get()
    time.sleep(1)
    driver.fullscreen_window()
    kullanici = driver.find_element(By.ID,'username')
    kullanici.click()
    kullanici.send_keys(logins)
    time.sleep(1)
    sifre = driver.find_element(By.ID,'userpassword')
    sifre.click()
    time.sleep(1)
    sifre.send_keys(password)
    time.sleep(1)
    giris = driver.find_element(By.CLASS_NAME,'Buttonstyles__ButtonWrapper-sc-o9c5ps-1')
    giris.click()
    time.sleep(1)
    #driver.set_page_load_timeout(3)
    driver.get("https://www.pochta.ru/parcels")
    driver.fullscreen_window()
    time.sleep(1)
    driver.execute_script("window.stop();")
    
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
   
    time.sleep(1)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    
    sehir = driver.find_element(By.ID,'addressFrom')
    sehir.click()
    sehir.send_keys('г Москва')
    sehir.send_keys(Keys.ENTER)
    time.sleep(1)
    sehir.click()
    sehir.send_keys(Keys.ARROW_DOWN)
    sehir.send_keys(Keys.ENTER)
    kuda = driver.find_element(By.ID,'addressTo')
    time.sleep(1)
    kuda.click()
    alici_adres = page3entry4.get()
    kuda.send_keys(alici_adres)
    time.sleep(1)
    kuda.send_keys(Keys.ENTER)
    otkuda = driver.find_element(By.ID,'addressFrom')
    otkuda.click()
    otkuda.send_keys(Keys.ENTER)
    time.sleep(1)
    kuda.click()
    kuda.send_keys(Keys.ARROW_DOWN)
    kuda.send_keys(Keys.ENTER)
    time.sleep(1)
    kantar = page3entry5.get()
    #driver.execute_script("arguments[0].scrollIntoView():",agirlik)
    agirlik = driver.find_element(By.ID,'weight')
    time.sleep(1)
    agirlik.click()
    agirlik.send_keys(kantar)
    time.sleep(1)
    agirlik.send_keys(Keys.ARROW_DOWN)
    agirlik.send_keys(Keys.ENTER)
    agirlik.click()
    time.sleep(1)
    #abicni = driver.find_element(By.NAME,'RadioButton__RadioButtonWrapper-sc-khtuca-2')
    #abicni.click()
    time.sleep(2)
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    fiyat = driver.find_element(By.CLASS_NAME,'Font-sc-le1wax-0')
    hesap = fiyat.text
    print(hesap)
    time.sleep(1)
    devam = driver.find_element(By.ID,'validateButton')
    devam.click()
    time.sleep(1)
    gonderen = page3entry1.get()
    gonderici = driver.find_element(By.ID,'senderName')
    gonderici.click()
    gonderici.send_keys(gonderen)
    gonderici.send_keys(Keys.ARROW_DOWN)
    gonderici.send_keys(Keys.ENTER)
    time.sleep(1)
    top = driver.find_element(By.ID,'recipientName')
    driver.execute_script("arguments[0].scrollIntoView();",top)
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    gonderici_adres = driver.find_element(By.ID,'senderAddress')
    time.sleep(1)
    gonderen_adres = page3entry2.get()
    #gonderici_adres.click()
    gonderici_adres.send_keys(' ',gonderen_adres)
    gonderici_adres.send_keys(Keys.ENTER)
    time.sleep(1)
    gonderici_adres.click()
    gonderici_adres.send_keys(Keys.ARROW_DOWN)
    gonderici_adres.send_keys(Keys.ENTER)
    time.sleep(1)
    gonderici_adres.send_keys(Keys.ENTER)
    gonderici_adres.click()
    gonderici_adres.send_keys(Keys.ENTER)
    time.sleep(1)
    alici = page3entry3.get()
    alicis = driver.find_element(By.ID,'recipientName')
    driver.execute_script("arguments[0].scrollIntoView();",alicis)
    alicis.click()
    alicis.send_keys(alici)
    time.sleep(1)
    alicis.send_keys(Keys.ENTER)
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    time.sleep(1)
    driver.fullscreen_window()
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    time.sleep(1)

    vops = driver.find_element(By.CSS_SELECTOR,'#main-content > div > div > div > div > div.GridBox-sc-172em67-0.kLPXOH > div.Contentstyles__ContentWrapper-sc-1te3qrt-0.kzgmFG > div > div > div.Box-sc-7ax6ia-0.TwkSG > div > div > div:nth-child(2)')
    #driver.execute_script("arguments[0].scrollIntoView();",vops)
    time.sleep(1)
    vops.click()
    time.sleep(1)
    goon = driver.find_element(By.ID,'submitButtonMobile')
    goon.click()
    time.sleep(2)
    driver.fullscreen_window()
    shpi = driver.find_element(By.XPATH,"//span[@data-testid= \"tracking.card-header-barcode\"]")
    kode = shpi.text
    print(kode)
    shtrixcode = StringVar()
    shtrixcode.set(kode)
    page3label.pack_forget()
    page2label.pack_forget()
    page2label2.place_forget()
    page2entry1.place_forget()
    page2label3.place_forget()
    page2entry2.place_forget()
    page2label4.place_forget()
    page2entry3.place_forget()
    page2label5.place_forget()
    page2entry4.place_forget()
    page2button1.place_forget()
    page2label.pack_forget()
    page2button2.place_forget()
    page3label.place_forget()
    page3label2.place_forget()
    page3entry1.place_forget()
    page3label3.place_forget()
    page3entry2.place_forget()
    page3label4.place_forget()
    page3entry3.place_forget()
    page3label5.place_forget()
    page3entry4.place_forget()
    page3button1.place_forget()
    page3button2.place_forget()
    page2label6.place_forget()
    page2entry5.place_forget()
    page3label6.place_forget()
    page3entry5.place_forget()
    page0label.place_forget()
    page0label2.place_forget()
    page0label3.place_forget()
    page0entry1.place_forget()
    page0entry2.place_forget()
    page0button1.place_forget()
    harfq.place_forget()
    harfw.place_forget()
    harfe.place_forget()
    harfr.place_forget()
    harft.place_forget()
    harfy.place_forget()
    harfu.place_forget()
    harfi.place_forget()
    harfo.place_forget()
    harfp.place_forget()
    harfx.place_forget()
    harff.place_forget()
    harfa.place_forget()
    harfs.place_forget()
    harfd.place_forget()
    harfff.place_forget()
    harfg.place_forget()
    harfh.place_forget()
    harfj.place_forget()
    harfk.place_forget()
    harfl.place_forget()
    harfjj.place_forget()
    harfjjj.place_forget()  
    harfee.place_forget()
    harfeee.place_forget()  
    harfoo.place_forget()
    harfoooo.place_forget()
    harfz.place_forget()  
    harfxxx.place_forget()  
    harfc.place_forget()
    harfv.place_forget()
    harfb.place_forget()
    harfn.place_forget()
    harfm.place_forget()
    harfdd.place_forget()
    harfrr.place_forget()
    probel.place_forget()
    sayi1.place_forget()
    sayi2.place_forget()
    sayi3.place_forget()
    sayi4.place_forget()
    sayi5.place_forget()
    sayi6.place_forget()
    sayi7.place_forget()
    sayi8.place_forget()
    sayi9.place_forget()
    sayi0.place_forget()
    harfddd.place_forget()
    harfrrr.place_forget()
    page2label7.place_forget()
    page2entry6.place_forget()
    page1label0.place(x=17,y=10)
    page4label1 = Label(root,text = 'Ваша номер отправление:',font=('arial',20))
    page4label = Label(root,textvariable=shtrixcode,font = ('arial',40))
    page4label.place(x=300,y=300)
    page4label1.place(x=320,y=250)    
    driver.close()

def pismo():
    driver=webdriver.Chrome(options=options)
    url = "https://www.pochta.ru/api/auth/login"
    driver.get(url)
    driver.fullscreen_window()
    time.sleep(2)
    loginn = page0entry1.get()
    passworda = page0entry2.get()
    kullanici = driver.find_element(By.ID,'username')
    kullanici.click()
    kullanici.send_keys(loginn)
    time.sleep(1)
    sifre = driver.find_element(By.ID,'userpassword')
    sifre.click()
    time.sleep(1)
    sifre.send_keys(passworda)
    time.sleep(1)
    giris = driver.find_element(By.CLASS_NAME,'Buttonstyles__ButtonWrapper-sc-o9c5ps-1')
    giris.click()
    time.sleep(2)
    driver.get("https://www.pochta.ru/letters")
    driver.fullscreen_window()
    driver.execute_script("window.stop();")
    time.sleep(1)
    sehir = page2entry6.get()
    agirlik = page2entry5.get()
    receiver_city = driver.find_element(By.NAME,'AddressTo')
    receiver_city.click()
    receiver_city.clear()
    receiver_city.send_keys(sehir)
    time.sleep(1)
    receiver_city.send_keys(Keys.ENTER)
    time.sleep(1)
    gram = driver.find_element(By.ID,'Weight')
    gram.send_keys(agirlik)
    time.sleep(1)
    gram.send_keys(Keys.ENTER)
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, 700)")
    time.sleep(1)
    zakaznoe = driver.find_element(By.XPATH,"//label[text()='Заказное']")
    time.sleep(1)
    zakaznoe.click()
    time.sleep(1)
    receiver_city.click()
    receiver_city.send_keys(Keys.DOWN)
    receiver_city.send_keys(Keys.ENTER)
    time.sleep(1)
    driver.get('https:www.pochta.ru/forms/letter?weight=20&activeKind=LETTER&title=%D0%97%D0%B0%D0%BA%D0%B0%D0%B7%D0%BD%D0%BE%D0%B5+%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE+20%C2%A0%D0%B3%2C+%D0%B2%26nbsp%3B%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D1%83&productType=LETTER&productTitle=%D0%9F%D0%B8%D1%81%D1%8C%D0%BC%D0%B0&shortTitle=%D0%97%D0%B0%D0%BA%D0%B0%D0%B7%D0%BD%D0%BE%D0%B5+%D0%BF%D0%B8%D1%81%D1%8C%D0%BC%D0%BE&type=LETTER&registered=true&noReturn=true&toCity=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&toCountry=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F+%D0%A4%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F&toRegion=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&toNormalizedAddress=%D0%B3+%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&toDistrict=&toIndex=101000&fromIndex=101000&fromCity=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&fromCountry=%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B0%D1%8F+%D0%A4%D0%B5%D0%B4%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F&fromRegion=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&fromNormalizedAddress=%D0%B3+%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&fromDistrict=&formless=true&cost=63')
    driver.fullscreen_window()
    time.sleep(1)
    gonderen = driver.find_element(By.ID,'Sender')
    time.sleep(1)
    isim = page2entry1.get()
    gonderen.send_keys(isim)
    gonderen.send_keys(Keys.ENTER)
    driver.execute_script("window.scrollTo(0,400)")
    time.sleep(1)
    gonderen_adres = driver.find_element(By.NAME,'SenderAddress')
    time.sleep(1)
    gonderen_adres.click()
    time.sleep(1)
    adres = page2entry2.get()
    gonderen_adres.send_keys(' ',adres)
    time.sleep(1)
    gonderen_adres.send_keys(Keys.ENTER)
    time.sleep(1)
    gonderen_adres.click()
    time.sleep(1)
    gonderen_adres.send_keys(Keys.DOWN)
    gonderen_adres.send_keys(Keys.ENTER)
    time.sleep(1)
    alici_adi = driver.find_element(By.ID,'Recipient')
    time.sleep(1)
    isim2 = page2entry3.get()
    alici_adi.send_keys(isim2)
    alici_adi.send_keys(Keys.ENTER)
    time.sleep(1)
    alana = driver.find_element(By.NAME,'RecipientAddress')
    alana.click()
    for i in range(9):alana.send_keys(Keys.BACKSPACE)
    time.sleep(2)
    alan = page2entry4.get()
    alana.send_keys(' ',alan)
    time.sleep(2)
    alana.send_keys(Keys.ENTER)
    alana.click()
    time.sleep(2)
    alana.send_keys(Keys.DOWN)
    alana.send_keys(Keys.ENTER)
    time.sleep(3)
    alici_numara = driver.find_element(By.ID,'SenderIndex')
    print(alici_numara.text)
    gonderen_numara = driver.find_element(By.ID,'RecipientIndex')
    print(gonderen_numara.text)
    button = driver.find_element(By.XPATH,'//button[text()="Получить трек-номер"]')
    button.click()
    time.sleep(1)
    kod = driver.find_element(By.XPATH,"//span[@data-testid= \"tracking.card-header-barcode\"]")
    print('Ваш номер отправлении: ',kod.text)
    shtrixcode = StringVar()
    shtrixcode.set(kod.text)
    harfq.place_forget()
    harfw.place_forget()
    harfe.place_forget()
    harfr.place_forget()
    harft.place_forget()
    harfy.place_forget()
    harfu.place_forget()
    harfi.place_forget()
    harfo.place_forget()
    harfp.place_forget()
    harfx.place_forget()
    harff.place_forget()
    harfa.place_forget()
    harfs.place_forget()
    harfd.place_forget()
    harfff.place_forget()
    harfg.place_forget()
    harfh.place_forget()
    harfj.place_forget()
    harfk.place_forget()
    harfl.place_forget()
    harfjj.place_forget()  
    harfee.place_forget() 
    harfoo.place_forget()
    harfz.place_forget()  
    harfxxx.place_forget()
    harfxxxx.place_forget()  
    harfc.place_forget()
    harfv.place_forget()
    harfb.place_forget()
    harfn.place_forget()
    harfm.place_forget()
    harfdd.place_forget()
    harfrr.place_forget()
    probel.place_forget()
    sayi1.place_forget()
    sayi2.place_forget()
    sayi3.place_forget()
    sayi4.place_forget()
    sayi5.place_forget()
    sayi6.place_forget()
    sayi7.place_forget()
    sayi8.place_forget()
    sayi9.place_forget()
    sayi0.place_forget()
    page2label7.place_forget()
    page2entry6.place_forget()
    page2label.place_forget()
    page2entry1.place_forget()
    page2entry2.place_forget()
    page2button2.place_forget()
    page2label.place_forget()
    page2label2.place_forget()
    page2entry1.place_forget()
    page2label3.place_forget()
    page2entry2.place_forget()
    page2label4.place_forget()
    page2entry3.place_forget()
    page2label5.place_forget()
    page2entry4.place_forget()
    page2button1.place_forget()
    page2button2.place_forget()
    page2label6.place_forget()
    page2entry5.place_forget()
    harfddd.place_forget()
    harfrrr.place_forget()
    harfoooo.place_forget()
    harfjjj.place_forget()
    harfeee.place_forget()
    page4label1 = Label(root,text = 'Ваша номер отправление:',font=('arial',20))
    page4label = Label(root,textvariable=shtrixcode,font = ('arial',40))
    page4label.place(x=300,y=300)
    page4label1.place(x=300,y=250)
    driver.close()


def client_posilka():
    ver = variable.get()
    if ver == 'Посылка':
        poss()
    elif w == 'Письмо':
        piss()


def poss():
    otpravitel = 'кырмызыгедик уфук'
    adres_otpravitel = 'островитянова дом 5к2 кв 66'
    poluchatel = page4entry1.get()
    adres_poluchatel = page4lentry2.get()
    tasi = page4entry3.get()
    sehir = page4entry4.get()
    logina = '89251771507'
    paroli = 'Ufuk1478963'
    driver=webdriver.Chrome(options=options)
    #driver=webdriver.Chrome('/lib/chromium-browser/chromedriver',options=options)
    driver.get('https://www.pochta.ru/api/auth/login')
    time.sleep(1)
    driver.fullscreen_window()
    kullanici = driver.find_element(By.ID,'username')
    kullanici.click()
    kullanici.send_keys(logina)
    time.sleep(1)
    sifre = driver.find_element(By.ID,'userpassword')
    sifre.click()
    time.sleep(1)
    sifre.send_keys(paroli)
    time.sleep(1)
    giris = driver.find_element(By.CLASS_NAME,'Buttonstyles__ButtonWrapper-sc-o9c5ps-1')
    giris.click()
    time.sleep(1)
    #driver.set_page_load_timeout(3)
    driver.get("https://www.pochta.ru/parcels")
    driver.fullscreen_window()
    time.sleep(1)
    driver.execute_script("window.stop();")
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    time.sleep(1)
    kuda = driver.find_element(By.ID,'addressTo')
    time.sleep(1)
    kuda.click()
    kuda.send_keys(adres_poluchatel)
    time.sleep(1)
    kuda.send_keys(Keys.ARROW_DOWN)
    kuda.send_keys(Keys.ENTER)
    otkuda = driver.find_element(By.ID,'addressFrom')
    otkuda.click()
    otkuda.send_keys(adres_otpravitel)
    otkuda.send_keys(Keys.ENTER)
    time.sleep(1)
    otkuda.click()
    otkuda.send_keys(Keys.ARROW_DOWN)
    otkuda.send_keys(Keys.ENTER)
    time.sleep(1)
    agirlik = driver.find_element(By.ID,'weight')
    time.sleep(1)
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    
    agirlik.click()
    agirlik.send_keys(tasi)
    time.sleep(1)
    agirlik.send_keys(Keys.ARROW_DOWN)
    agirlik.send_keys(Keys.ENTER)
    
    time.sleep(1)
    #abicni = driver.find_element(By.NAME,'RadioButton__RadioButtonWrapper-sc-khtuca-2')
    #abicni.click()
    time.sleep(2)
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    fiyat = driver.find_element(By.CLASS_NAME,'Font-sc-le1wax-0')
    hesap = fiyat.text
    print(hesap)
    time.sleep(1)
    devam = driver.find_element(By.ID,'validateButton')
    devam.click()
    time.sleep(1)
    gonderici = driver.find_element(By.ID,'senderName')
    gonderici.click()
    gonderici.send_keys(otpravitel)
    gonderici.send_keys(Keys.ARROW_DOWN)
    gonderici.send_keys(Keys.ENTER)
    time.sleep(1)
    top = driver.find_element(By.ID,'recipientName')
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    #gonderici_adres = driver.find_element(By.ID,'senderAddress')
    #time.sleep(1)
    #gonderici_adres.send_keys(' ',adres_otpravitel)
    #gonderici_adres.send_keys(Keys.ENTER)
    #time.sleep(1)
    #gonderici_adres.click()
    #gonderici_adres.send_keys(Keys.ARROW_DOWN)
    #gonderici_adres.send_keys(Keys.ENTER)
    #time.sleep(1)
    #gonderici_adres.send_keys(Keys.ENTER)
    #gonderici_adres.click()
    #gonderici_adres.send_keys(Keys.ENTER)
    #time.sleep(1)
    alicis = driver.find_element(By.ID,'recipientName')
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    alicis.click()
    alicis.send_keys(poluchatel)
    alicis.send_keys(Keys.ENTER)
    alicis.send_keys(Keys.ENTER)
    #driver.find_element_by_css_selector("body").send_keys(Keys.CONTROL, Keys.END)
    time.sleep(1) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    #vops = driver.find_element(By.CSS_SELECTOR,'#main-content > div > div > div > div > div.GridBox-sc-172em67-0.kLPXOH > div.Contentstyles__ContentWrapper-sc-1te3qrt-0.kzgmFG > div > div > div.Box-sc-7ax6ia-0.TwkSG > div > div > div:nth-child(2)')
    #driver.execute_script("arguments[0].scrollIntoView();",vops)
    vops = driver.find_element(By.XPATH,'//*[@id="main-content"]/div/div/div/div/div[1]/div[2]/div/div/div[3]/section[4]/div[2]/div/div/div/div/div/div[2]')
    time.sleep(1)
    vops.click()
    driver.fullscreen_window()
    time.sleep(1)
    goon = driver.find_element(By.ID,'submitButtonMobile')
    goon.click()
    time.sleep(2)
    shpi = driver.find_element(By.XPATH,"//span[@data-testid= \"tracking.card-header-barcode\"]")
    kode = shpi.text
    print(kode)
    shtrixcode = StringVar()
    shtrixcode.set(kode)
    page3label.pack_forget()
    page2label.pack_forget()
    page2label2.place_forget()
    page2entry1.place_forget()
    page2label3.place_forget()
    page2entry2.place_forget()
    page2label4.place_forget()
    page2entry3.place_forget()
    page2label5.place_forget()
    page2entry4.place_forget()
    page2button1.place_forget()
    page2label.pack_forget()
    lang.place_forget()
    page2button2.place_forget()
    page3label.place_forget()
    page3label2.place_forget()
    page3entry1.place_forget()
    page3label3.place_forget()
    page3entry2.place_forget()
    page3label4.place_forget()
    page3entry3.place_forget()
    page3label5.place_forget()
    page3entry4.place_forget()
    page3button1.place_forget()
    page3button2.place_forget()
    page2label6.place_forget()
    page2entry5.place_forget()
    page3label6.place_forget()
    page3entry5.place_forget()
    page0label.place_forget()
    page0label2.place_forget()
    page0label3.place_forget()
    page0entry1.place_forget()
    page0entry2.place_forget()
    page0button1.place_forget()
    harfq.place_forget()
    harfw.place_forget()
    harfe.place_forget()
    harfr.place_forget()
    harft.place_forget()
    harfy.place_forget()
    harfu.place_forget()
    harfi.place_forget()
    harfo.place_forget()
    harfp.place_forget()
    harfx.place_forget()
    harff.place_forget()
    harfa.place_forget()
    harfs.place_forget()
    harfd.place_forget()
    harfff.place_forget()
    harfg.place_forget()
    harfh.place_forget()
    harfj.place_forget()
    harfk.place_forget()
    harfl.place_forget()
    harfjj.place_forget()
    harfjjj.place_forget()  
    harfee.place_forget()
    harfeee.place_forget()  
    harfoo.place_forget()
    harfoooo.place_forget()
    harfz.place_forget()  
    harfxxx.place_forget()  
    harfc.place_forget()
    harfv.place_forget()
    harfb.place_forget()
    harfn.place_forget()
    harfm.place_forget()
    harfdd.place_forget()
    harfrr.place_forget()
    probel.place_forget()
    sayi1.place_forget()
    sayi2.place_forget()
    sayi3.place_forget()
    sayi4.place_forget()
    sayi5.place_forget()
    sayi6.place_forget()
    sayi7.place_forget()
    sayi8.place_forget()
    sayi9.place_forget()
    sayi0.place_forget()
    harfddd.place_forget()
    harfrrr.place_forget()
    page2label7.place_forget()
    page2entry6.place_forget()
    page4label0.place_forget()
    
    page4entry1.place_forget()
    page4label2.place_forget()
    page4lentry2.place_forget()
    page4label3.place_forget()
    page4entry3.place_forget()
    page4label4.place_forget()
    page4entry4.place_forget()
    page4button1.place_forget()
    page4button2.place_forget()
    w.place_forget()
    page1label0.place(x=17,y=10)
    page4label1 = Label(root,text = 'Ваша номер отправление:',font=('arial',20))
    page4label = Label(root,textvariable=shtrixcode,font = ('arial',40))
    page4label.place(x=300,y=300)
    page4label1.place(x=320,y=250)    
    driver.close()

page0label=Label(root,text='Вход в система',font=('arial',20,'bold'),image=backr)
page0label2 = Label(root,text='Номер телефона или электронная почта:')
page0label3 = Label(root,text='Пароль:')
page0entry1= Entry(borderwidth=5,width=50)
page0entry2=Entry(borderwidth=5,width=50)
page0button1=Button(root,text='Логин',font=('arial',13,'bold'),relief=RAISED,pady=40,padx=40,bg='white',command=page1)
page0button2 = Button(root,text='у меня есть карта Почты',font=('arial',13,'bold'),relief=RAISED,pady=40,padx=40,bg='white',command=nfc)

page1label0 = Label(root,image=backr)
page1btn = Button(root,text='Отправить письмо',font=('arial',15,'bold'),pady=60,padx=60,bg='white',relief=RAISED,command=page2)
page1label = Label(root,text='Прием писем/посылка',font=('arial',30,'bold'),bg='white')
page1button2 = Button(root,text='Отправить посылку',font=('arial',15,'bold'),pady=60,padx=60,bg='white',command=page3)
page1button3 = Button(root,text='Назад',font=('arial',15,'bold'),pady=60,padx=80,bg='white',command=page0)

page2label = Label(root,text='Отправить письмо',font=('arial',20,'bold'),image=backr)
page2label2 = Label(root,text='От кого:')
page2entry1= Entry(width=50,borderwidth=5)
page2entry1.insert(0,'ФИО')
page2label3 = Label(root,text='Адрес:')
page2entry2= Entry(width=50,borderwidth=5)
page2entry2.insert(0,'Адрес отправителя')
page2label4= Label(root,text='Кому:')
page2entry3= Entry(width=50,borderwidth=5)
page2entry3.insert(0,'кому отправляете')
page2label5 = Label(root,text='Адрес получатель:')
page2entry4 = Entry(width=50,borderwidth=5)
page2entry4.insert(0,'напишите адрес получателя')
page2label6 = Label(root,text='Вес:')
page2entry5 = Entry(width=50,borderwidth=5)
page2entry5.insert(0,'напишите примерный вес')
page2label7 = Label(root,text='Город:')
page2entry6 = Entry(width=20,borderwidth=5)
page2entry6.insert(0,'Город получателя')
page2button1 = Button(root,text='Назад',padx=60,pady=20,bg='white',command=page1)
page2button2 = Button(root,text='Отпрвавить',bg='white',padx=50,pady=20,command=pismo)

page3label = Label(root,text='Отправить посылка',font=('arial',20,'bold'),image=backr)
page3label2 = Label(root,text='От кого:')
page3entry1= Entry(width=50,borderwidth=5)
page3entry1.insert(0,'ФИО')
page3label3 = Label(root,text='Адрес:')
page3entry2= Entry(width=50,borderwidth=5)
page3entry2.insert(0,'напишите адрес отправителя')
page3label4= Label(root,text='Кому:')
page3entry3= Entry(width=50,borderwidth=5)
page3entry3.insert(0,'Кому отправляете')
page3label5 = Label(root,text='Адрес получателя:')
page3entry4 = Entry(width=50,borderwidth=5)
page3entry4.insert(0,'напишите адрес получателя')
page3button1 = Button(root,text='Назад',padx=72,pady=14,bg='white',command=page1)
page3button2 = Button(root,text='Отправить',padx=60,pady=80,bg='white',command=posilka)
page3label6 = Label(root,text='Вес:')
page3entry5 = Entry(width=50,borderwidth=5)
page3entry5.insert(0,'Напишите примерный вес')

page4label0 = Label(root,text='Прием писем/посылок',font=('arial',20,'bold'))
page4label1 = Label(root,text = 'Кому:')
page4entry1 = Entry(width = 50,borderwidth=5)
page4entry1.insert(0,'напишите фио получателя')
page4label2 = Label(root,text = 'Куда:')
page4lentry2 = Entry(width= 50,borderwidth=5)
page4lentry2.insert(0,'напишите адрес получателя')
page4label3 = Label(root,text='Вес:')
page4entry3 = Entry(width=50,borderwidth=5)
page4entry3.insert(0,'напишите примерный вес')
page4label4 = Label(root,text='Город:')
page4entry4 = Entry(width=50,borderwidth=5)
page4entry4.insert(0,'напишите какой город отправляйте')
page4button1 = Button(root,text = 'Отправить',relief=RAISED,font=('arial','20','bold'),pady=15,padx=15,command=client_posilka)
page4button2 = Button(root,text='Назад',relief=RAISED,font=('arial','20','bold'),pady=15,padx=45,command=page0)
variable = StringVar(root)
variable.set('Выбирайте пожалуйста что хотите отправить')
w = OptionMenu(root,variable,"Посылка","Письмо")

harfq = Button(root,text='й',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('q'),pady=15,padx=15)
harfw = Button(root,text='ц',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('w'),pady=15,padx=15)
harfe = Button(root,text='у',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('e'),pady=15,padx=15)
harfr = Button(root,text='к',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('r'),pady=15,padx=15)
harft = Button(root,text='е',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('t'),pady=15,padx=15)
harfy = Button(root,text='н',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('y'),pady=15,padx=15)
harfu = Button(root,text='г',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('u'),pady=15,padx=15)
harfi = Button(root,text='ш',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('i'),pady=15,padx=15)
harfo = Button(root,text='щ',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('o'),pady=15,padx=15)
harfp=Button(root,text='з',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('p'),pady=15,padx=15)
harfx = Button(root,text='х',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('['),pady=15,padx=15)
harff=Button(root,text='ъ',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press(']'),pady=15,padx=15)
harfa =Button(root,text='ф',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('a'),pady=15,padx=12)
harfs = Button(root,text='ы',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('s'),pady=15,padx=12)
harfd = Button(root,text='в',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('d'),pady=15,padx=13)
harfff = Button(root,text='а',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('f'),pady=15,padx=15)
harfg = Button(root,text='п',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('g'),pady=15,padx=15)
harfh = Button(root,text='р',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('h'),pady=15,padx=15)
harfj = Button(root,text='о',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('j'),pady=15,padx=15)
harfk = Button(root,text='л',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('k'),pady=15,padx=15)
harfl = Button(root,text='д',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('l'),pady=15,padx=15)
harfjjj = Button(root,text='ж',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press(';'),pady=15,padx=15)
harfeee = Button(root,text='э',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press(' " '),pady=15,padx=15)
harfoooo = Button(root,text='Удалить',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('backspace'),pady=15,padx=25)
harfz = Button(root,text='я',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('z'),pady=15,padx=15)
harfxxx = Button(root,text='ч',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('x'),pady=15,padx=15)
harfc = Button(root,text='с',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('c'),pady=15,padx=15)
harfv = Button(root,text='м',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('v'),pady=15,padx=13)
harfb = Button(root,text='и',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('b'),pady=15,padx=15)
harfn = Button(root,text='т',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('n'),pady=15,padx=16)
harfm = Button(root,text='ь',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('m'),pady=15,padx=15)
harfddd = Button(root,text='б',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press(','),pady=15,padx=15)
harfrrr = Button(root,text='ю',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('.'),pady=15,padx=15)
probel = Button(root,text='Пробел',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('space'),pady=15,padx=80)
sayi1 = Button(root,text='1',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('1'),pady=15,padx=25)
sayi2 = Button(root,text='2',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('2'),pady=15,padx=25)
sayi3 = Button(root,text='3',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('3'),pady=15,padx=25)
sayi4 = Button(root,text='4',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('4'),pady=15,padx=25)
sayi5 = Button(root,text='5',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('5'),pady=15,padx=25)
sayi6 = Button(root,text='6',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('6'),pady=15,padx=25)
sayi7 = Button(root,text='7',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('7'),pady=15,padx=16)
sayi8 = Button(root,text='8',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('8'),pady=15,padx=16)
sayi9 = Button(root,text='9',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('9'),pady=15,padx=15)
sayi0 = Button(root,text='0',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('0'),pady=15,padx=17)


harfqq = Button(root,text='q',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('q'),pady=15,padx=18)
harfww = Button(root,text='w',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('w'),pady=15,padx=15)
harfee = Button(root,text='e',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('e'),pady=15,padx=18)
harfrr = Button(root,text='r',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('r'),pady=15,padx=18)
harftt = Button(root,text='t',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('t'),pady=15,padx=19)
harfyy = Button(root,text='y',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('y'),pady=15,padx=16)
harfuu = Button(root,text='u',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('u'),pady=15,padx=16)
harfii = Button(root,text='i',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('i'),pady=15,padx=20)
harfoo = Button(root,text='o',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('o'),pady=15,padx=16)
harfpp=Button(root,text='p',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('p'),pady=15,padx=25)
harfaa =Button(root,text='a',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('a'),pady=15,padx=18)
harfss = Button(root,text='s',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('s'),pady=15,padx=18)
harfdd = Button(root,text='d',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('d'),pady=15,padx=18)
harffff = Button(root,text='f',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('f'),pady=15,padx=18)
harfgg = Button(root,text='g',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('g'),pady=15,padx=15)
harfhh = Button(root,text='h',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('h'),pady=15,padx=15)
harfjj = Button(root,text='j',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('j'),pady=15,padx=20)
harfkk = Button(root,text='k',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('k'),pady=15,padx=16)
harfll = Button(root,text='l',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('l'),pady=15,padx=20)
harfooo = Button(root,text='Del',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('backspace'),pady=15,padx=13)
harfzz = Button(root,text='z',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('z'),pady=15,padx=19)
harfxxxx = Button(root,text='x',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('x'),pady=15,padx=18)
harfcc = Button(root,text='c',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('c'),pady=15,padx=19)
harfvv = Button(root,text='v',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('v'),pady=15,padx=15)
harfbb = Button(root,text='b',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('b'),pady=15,padx=15)
harfnn = Button(root,text='n',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('n'),pady=15,padx=16)
harfmm = Button(root,text='m',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('m'),pady=15,padx=12)
probell = Button(root,text='Space',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('space'),pady=15,padx=50)
sayii1 = Button(root,text='1',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('1'),pady=15,padx=25)
sayii2 = Button(root,text='2',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('2'),pady=15,padx=25)
sayii3 = Button(root,text='3',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('3'),pady=15,padx=25)
sayii4 = Button(root,text='4',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('4'),pady=15,padx=25)
sayii5 = Button(root,text='5',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('5'),pady=15,padx=25)
sayii6 = Button(root,text='6',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('6'),pady=15,padx=25)
sayii7 = Button(root,text='7',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('7'),pady=15,padx=16)
sayii8 = Button(root,text='8',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('8'),pady=15,padx=16)
sayii9 = Button(root,text='9',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('9'),pady=15,padx=15)
sayii0 = Button(root,text='0',relief=RAISED,font=('arial','20','bold'),command = lambda:py.press('0'),pady=15,padx=17)
lang = Button(root,text='Lang',relief=RAISED,font=('arial','20','bold'),command = change_language,pady=15,padx=17)
capsl = Button(root,text='Caps',relief=RAISED,font=('arial','20','bold'),command = upper_letter,pady=15,padx=17)

page0()

root.mainloop()
 
